language: minimal
services:
- docker
install:
- docker pull popcodeorg/popcode:latest
- docker build --pull --cache-from popcodeorg/popcode:latest --tag popcode .
script:
- docker run --env NODE_ENV=test popcode yarn test
- >-
  docker run
  --env NODE_ENV=production
  --env FIREBASE_APP
  --env FIREBASE_API_KEY
  --env FIREBASE_CLIENT_ID
  --env GIT_REVISION="$TRAVIS_COMMIT"
  --env GOOGLE_ANALYTICS_TRACKING_ID
  --volume="$TRAVIS_BUILD_DIR/dist:/app/dist"
  popcode
  yarn run gulp build
- >-
  docker run
  --volume=$TRAVIS_BUILD_DIR/dist:/app/dist
  popcode
  yarn run eslint --no-eslintrc --env es5 dist
- docker run popcode script/check-duplicate-dependencies
before_deploy:
- >-
  docker run
  --env FIREBASE_APP
  --env FIREBASE_SECRET
  popcode
  yarn run gulp syncFirebase
deploy:
- provider: s3
  access_key_id: AKIAJY2GYDQBE4HFF32Q
  secret_access_key:
    secure: qqkSdpnlOM80HavspUc/S4OpohDAkbDqaCKQTw08j2/CaU0LwN335CVQhDZ4Oskgr6y5evx6LrTU0BNiDfzcMIEykokV1ZCPLuWLrHo/ZtCSIU+3ikVErY/0qZH4FdZ1h/Q1FP5gTDydP0QbXWkQsQQg1cgg2NTX4/BsTTT9nBRJeg4Gdm9ARLW0b3SGutW13tW8fuRG9YrNJs6gKZsZ6FhP1ru4T47tdsbphV1IsedZv8nU7dGnWQj67//4OpAHOi1KOm6K1CprNa35Kw7D/+n6786skbPi7Tsu7UbIVMWD+Jy1c2xtz3mqinIbyS8spzLd3kbDV+BRvIYXXHpC6B4gGhyRd+ohN+WcoDQZJha2PaOfIPfAxPhK2IKO6h+6i8Q0CK4/x4Yd8PurVHrB8KEyPrMHPa42abMTTeRLs7OAjrtM7dWucngCvW6fBqhpgp36cRDZeXLKjywkapo1/6l64fjkM+wGkYFkI5i6qzEAr0JvBrIeTDiymz1Oitf3Uio+vs4hfjXegQansq5l/mXtMdI9DfNrKm/R2zpUp1qS7i+v1MfnhAxd8NOEGYpT75sJbSVca0jgnkLXcja6+O4oRswx4maA+BTiIcwknAn6B4Rupf8U0Tnt3s/pFu6Ih6lnMo6rpeBkV7FO1Bwyv59zyxZS8Z23ec+v7+TZ/iE=
  bucket: popcode.org
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  on:
    repo: popcodeorg/popcode
    branch: master
- provider: s3
  access_key_id: AKIAJY2GYDQBE4HFF32Q
  secret_access_key:
    secure: qqkSdpnlOM80HavspUc/S4OpohDAkbDqaCKQTw08j2/CaU0LwN335CVQhDZ4Oskgr6y5evx6LrTU0BNiDfzcMIEykokV1ZCPLuWLrHo/ZtCSIU+3ikVErY/0qZH4FdZ1h/Q1FP5gTDydP0QbXWkQsQQg1cgg2NTX4/BsTTT9nBRJeg4Gdm9ARLW0b3SGutW13tW8fuRG9YrNJs6gKZsZ6FhP1ru4T47tdsbphV1IsedZv8nU7dGnWQj67//4OpAHOi1KOm6K1CprNa35Kw7D/+n6786skbPi7Tsu7UbIVMWD+Jy1c2xtz3mqinIbyS8spzLd3kbDV+BRvIYXXHpC6B4gGhyRd+ohN+WcoDQZJha2PaOfIPfAxPhK2IKO6h+6i8Q0CK4/x4Yd8PurVHrB8KEyPrMHPa42abMTTeRLs7OAjrtM7dWucngCvW6fBqhpgp36cRDZeXLKjywkapo1/6l64fjkM+wGkYFkI5i6qzEAr0JvBrIeTDiymz1Oitf3Uio+vs4hfjXegQansq5l/mXtMdI9DfNrKm/R2zpUp1qS7i+v1MfnhAxd8NOEGYpT75sJbSVca0jgnkLXcja6+O4oRswx4maA+BTiIcwknAn6B4Rupf8U0Tnt3s/pFu6Ih6lnMo6rpeBkV7FO1Bwyv59zyxZS8Z23ec+v7+TZ/iE=
  bucket: popcode.school
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  on:
    repo: popcodeorg/popcode
    branch: master
- provider: script
  script: >-
    echo "$DOCKER_PASSWORD" |
    docker login -u "$DOCKER_USERNAME" --password-stdin &&
    docker tag popcode popcodeorg/popcode &&
    docker push popcodeorg/popcode
  on:
    repo: popcodeorg/popcode
    branch: master

after_deploy:
- >
  docker run
  --env CLOUDFLARE_EMAIL
  --env CLOUDFLARE_KEY
  --env CLOUDFLARE_ZONE
  --env HOSTNAME
  popcode
  yarn run gulp purgeCache
notifications:
  slack:
    secure: IJ0LSnahbfPFMFFgEK+wwSYEUWjJ2AFZz89oSmzSuKqEchM7AA2tpkCAPvN37cUksPE4YozVXxx++SQ4j+fk1lmhhddEUYO9ueB/UqD3iu0xCFR/CJ30ka7QDkfzkatKkn0H8MVU3FwEJ6ZbHJR2zJVUALPFw7AQ08EE4GpTC2TfWSiYuv1AnuVUC8ZkvGBjwFN1lQrAnHFS62sreNmYtBR0FHHo9DEE+NanYdtLnFYyGeDauWx7I1ERT1vnv4G+0vx5Guu7TGwC1uzHCTlciqSGPeaifaC+uXR/8VaTabZS4G1PsR8ROYt3S/RFtCEAfuhBvlcWdNnfLH7/xLhET4W35H/hhHmSaMYJCy/gnQW/bXfLCxtO5/luwM5nOM4NeQcRybqreBL/q4K78giw6ttpTo5EumBxXrYKo4PRWfOWkOhePotQ/IRzpsoMqFHxzlJxv9HPSnFb+11OTe3BsxfWpsHs233eIBpKYOcjpzXPP4GSq7FH2V7jL2lg6Cc81XUK2v8upJpPoWRRfM52LxemNi+uEMBrgLro6VA2O5qRDN/+mhr8wYS4dLms5uk6Hq87UA9xhlIUl0P9d6kfN0vHi+QzxLMLvA1ateFncaG7MKTgMNjsckziKlR2B8FZ1c3lT55RB/zfojGzrDs0l7TCKB+WKP5uPJEWw5/UC2A=
