version: '3'
services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - bower_components:/app/bower_components
      - npm_cache:/root/.npm
    tmpfs:
      - /app/dist
    environment:
      - DEBUG
      - PROFILE_BUILD
volumes:
  npm_cache:
  node_modules:
  bower_components:
