version: '3'
services:
  app:
    build: .
    command: yarn dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
      - npm_cache:/root/.npm
      - yarn_cache:/usr/local/share/.cache/yarn
    tmpfs:
      - /app/dist
    environment:
      - DEBUG
      - PROFILE_BUILD
volumes:
  node_modules:
  npm_cache:
  yarn_cache:
